FROM pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime
RUN pip install gdown -q
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install git vim python3-opencv -yq
RUN git clone -q https://github.com/PeterL1n/BackgroundMattingV2
RUN cd BackgroundMattingV2 && pip install -r requirements.txt
RUN gdown https://drive.google.com/uc?id=1ErIAsB_miVhYL9GDlYUmfbqlV293mSYf -O model.pth -q
#RUN gdown https://drive.google.com/uc?id=1tCEk8FE3WGrr49cdL8qMCqHptMCAtHRU -O /tmp/src.mp4 -q
#RUN gdown https://drive.google.com/uc?id=1wAR3JjnTO60B_DUr7ruIJj0Z2pcIGkyP -O /tmp/bgr.png -q
RUN pip install qdi fastapi uvicorn jinja2 aiofiles python-multipart

RUN apt update && apt install curl git cmake ack g++ python3-dev vim-youcompleteme tmux -yq
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/qooba/vim-python-ide/master/setup.sh)"

ENV PYTHONPATH="/app:${PYTHONPATH}"
WORKDIR /app
CMD bin/bash
